services:
    frontend-app:
        build:
            context: ./frontend
        ports:
            - "3000:80"
    
    server:
        links: 
            - mysql
        build:
            context: ./backend
        ports: 
            - "5000:5000"
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_USER=root
            - MYSQL_PASSWORD=testfortask
            - MYSQL_DATABASE=task
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
    
    mysql:
        container_name: mysql
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=testfortask
            - MYSQL_DATABASE=task
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptestfortask"]
            timeout: 5s
            retries: 10
volumes:
    mysql-data:
