#!/bin/bash
MYSQL_PASSWORD="testfortask"
MYSQL_DATABASE="task"
CONTAINER_NAME="mysql"

SQL_COMMAND=$(cat << EOF
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};
USE ${MYSQL_DATABASE};
CREATE TABLE IF NOT EXISTS responses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR(500) NOT NULL
);
EOF
)

docker exec -i $CONTAINER_NAME mysql -u root -p$MYSQL_PASSWORD -e "$SQL_COMMAND"